---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in
title: "Curriculum Vitae"
author: Pierrick Kinif
orcid: "Updated on 5th June 2018"
jobtitle: "Fresh Finance Graduate - In a Process to Learn Top Data Analytics Skills"
address: "Rue Albert 1er, 126 6780 Wolkrange, Belgium"
fontawesome: yes
email: pierrick-kinif@hotmail.be
github: pkinif
phone: "+32 478 113 485"
web: pkinif.github.io
updated: no
keywords: RMarkdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{lettrine}
---
\vspace{1cm}

\lettrine{L}orem ipsum dolor sit amet, consectetur adipisicing elit. Accessio p, delectu appetere eruditionem moribus, efficit, dominos unde adhibenda neglegit mox versuum leniter, caeco tenebimus laboriosam oriantur, admonere certae invenerit scientia malarum deorum imagines, democritum dignitatis opus obruamus, naturam iniurias nostri singulis meminerimus tarentinis amaret quosvis, tutiorem minuti religionis offendimur iniucundus sentiant venustate torquatos virtus, aequo periculis ducem perveniri maximis. Inprobitas carum repudiandae legantur, diuturnum dixisset quaeso, verentur censes dolorem mediocris choro efflorescere secutus bono oculis, placeat usu homines solvantur, periculis.

# EDUCATION

*University of Luxembourg*, Cert. in Sust. Dvlp and Soc. Innov. \hfill 09/2017-Present

*FEA, University of São Paulo*, Erasmus Mundus \hfill 07/2016-01/2017

*University of Namur*, M.B.A, Distinction \hfill 09/2015-06/2018  

> **Thesis** | "Towards Green Companies: A Panel Data Study of The Environmental and Financial Performance Nexus", available on my [GitHub](https://github.com/pkinif/Thesis) account.

*University of Namur*, B.B.A \hfill 09/2012-09/2015

*CE Saint-Joseph of Chimay*, High School, General Studies \hfill 09/2007-06/2012

# EXPERIENCE

*Assistant, Sustainability Practice at [IMS Luxembourg](http://imslux.lu/)* \hfill 09/2017-03/2018

> A catalyst for social innovation, IMS is the luxemburgish network that accompanies organisations in their commitment to Corporate Social Responsibility (i.e. CSR) by enhancing dialogue with their stakeholders. During this experience, first I contributed to the realization of a study aiming at evaluating the level of CSR of the companies network. Then I supported the organization...

*Credit Risk Data Analyst Intern at [BIL Luxembourg](https://www.bil.com/fr/Pages/index.aspx)* \hfill 01/2017-06/2017

> BIL is the oldest private banking group in the Grand Duchy and is among the country’s top three banks. My daily mission was to validate and to ensure consistency of credit risk database. This experience allowed me to develop strong knowledge in the Basle legislation and strengthen my data analytics and coputer coding skills (i.e. VBA, SQL and SAP BO). 

*Campus Consultant at [4uCampus](https://www.4ucampus.be/fr/)* \hfill 09/2015-03/2016

> 4uCampus is a Belgian company created in 1994 which offers reductions on newspapers, magazines, computers, softwares and printers to students and teachers. As Campus Consultant my main mission was: (i) sales of subscriptions of press titles to students and academic staffs, (ii) give speeches in public, (iii) prospecting. 

*Consulting Project at [Lunch Garden](https://www.lunchgarden.be/fr?gclid=EAIaIQobChMIx6rm_s282wIVhJ3VCh1brww1EAAYASAAEgK7A_D_BwE)* \hfill 09/2015-01/2016

> Lunch Garden is a Belgian fast food chain with more than 70 restaurants. With a team of 4 highly motivated junior consultants we carried out a consulting project to improve its employer branding.

*Barman and Server in Namur* \hfill 09/2012-12-2015

> Because being a student is costly, I had to work during my cursus. Mainly in the HORECA domain, I have learned how to make really tasty cocktails which I could gladly reproduce for my future colleagues.

# LANGUAGES

## Programming

> **Proficient**: R, Rmarkdown, Reproducible Research, \LaTeX\, GitHub, VBA, Pack Office

> **Familiar**:   SQL, SAP BO, Stata, SPSS, Oxmétrics, Html, Jekyll

## Written & spoken

> **French**:     Native Fluency

> **English**:    Professional working proficiency (i.e. C1 level)

> **Dutch**:      Limited working proficiency (i.e. B1 level)

> **Spanish**:    Elementary proficiency (i.e. A1 level)

# CERTIFICATION

> Data Analyst with R Certification, DataCamp, June 2018
